apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  creationTimestamp: null
  labels:
    app: bad-developer
    app.kubernetes.io/instance: bad-developer
  name: bad-developer
spec:
  ports:
  - name: 5555-tcp
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: bad-developer
    deploymentconfig: bad-developer
  sessionAffinity: None
  type: ClusterIP
